DeployToAzure/Controllers/DeployController.cs
using DeployToAzure.DAL;
using DeployToAzure.Hubs;
using DeployToAzure.Models;
using DeployToAzure.Web;
using LibGit2Sharp;
using Microsoft.AspNet.SignalR;
using Microsoft.IdentityModel.Clients.ActiveDirectory;
using Microsoft.WindowsAzure;
using Microsoft.WindowsAzure.Management.WebSites.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DeployToAzure.Controllers
{
    [System.Web.Mvc.Authorize]
    public class DeployController : Controller
    {
        string TenantId
        {
            get { return ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/tenantid").Value; }
        }

        string GetAccessToken()
        {
            string clientId = ConfigurationManager.AppSettings["ida:ClientID"];
            string appKey = ConfigurationManager.AppSettings["ida:Password"];
            string signedInUserID = ClaimsPrincipal.Current.FindFirst(ClaimTypes.NameIdentifier).Value;
            string userObjectID = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier").Value;

            try
            {
                // get a token for the Graph without triggering any user interaction (from the cache, via multi-resource refresh token, etc)
                ClientCredential clientcred = new ClientCredential(clientId, appKey);
                // initialize AuthenticationContext with the token cache of the currently signed in user, as kept in the app's EF DB
                AuthenticationContext authContext = new AuthenticationContext(string.Format("https://login.windows.net/{0}",
                    TenantId), new EFADALTokenCache(signedInUserID));
                AuthenticationResult result = authContext.AcquireTokenSilent("https://management.core.windows.net/",
                    clientcred, new UserIdentifier(userObjectID, UserIdentifierType.UniqueId));

                return result.AccessToken;
            }
            // if the above failed, the user needs to explicitly re-authenticate for the app to obtain the required token
            catch (Exception ee)
            {
                return null;
            }
        }

        void LogToSignalR(string message, string webSiteName)
        {
            var hub = GlobalHost.ConnectionManager.GetHubContext<StatusHub>();
            hub.Clients.Group(webSiteName).messageTraced(message);
        }

        List<SubscriptionViewModel> GetSubscriptions()
        {
            using (var subscriptionClient = CloudContext.Clients.CreateSubscriptionClient(
                new TokenCloudCredentials(GetAccessToken())
                ))
            {
                var result = subscriptionClient.Subscriptions.List();

                return result.Subscriptions.Select(x => new SubscriptionViewModel
                {
                    Name = x.SubscriptionName,
                    SubscriptionId = x.SubscriptionId,
                    ActiveDirectoryTenantId = x.ActiveDirectoryTenantId
                }).ToList();
            }
        }

        List<WebspaceViewModel> GetWebSpaces(string accessToken, string subscriptionId)
        {
            var ret = new List<WebspaceViewModel>();

            using (var webSiteManagementClient = CloudContext.Clients.CreateWebSiteManagementClient(
                    new TokenCloudCredentials(subscriptionId, accessToken)
                    ))
            {
                var webSpaceListResult = webSiteManagementClient.WebSpaces.List();

                webSpaceListResult.WebSpaces.ToList().ForEach(x => ret.Add(
                    new WebspaceViewModel
                    {
                        WebSpaceName = x.Name,
                        GeoRegion = x.GeoRegion
                    }));
            }

            return ret;
        }

        string CloneSiteRepository(string gitUrl, string webSiteName)
        {
            var localGitRepoDirName =
                Path.GetFileNameWithoutExtension(Path.GetRandomFileName());

            var srcFolder =
                Server.MapPath(string.Format("~/App_Data/{0}", localGitRepoDirName));

            LogToSignalR("Cloning repository", webSiteName);

            if (Directory.Exists(srcFolder))
                Directory.Delete(srcFolder, true);

            Repository.Clone(gitUrl, srcFolder);

            LogToSignalR("Cloned repository", webSiteName);

            return srcFolder;
        }

        // todo: clean up the parameters with an object
        void CreateAndDeployWebsite(string webSpaceName,
            string webSiteName,
            string webSiteSrcFolder,
            string subscriptionId,
            string accessToken)
        {
            using (var webSiteManagementClient = CloudContext.Clients.CreateWebSiteManagementClient(
                new TokenCloudCredentials(subscriptionId, accessToken)
                ))
            {
                var hostingPlanListResult = webSiteManagementClient.WebHostingPlans.List(webSpaceName);

                if (hostingPlanListResult.WebHostingPlans.Count == 0)
                {
                    webSiteManagementClient.WebHostingPlans.Create(webSpaceName,
                        new WebHostingPlanCreateParameters
                        {
                            Name = "QuickDeployed"
                        });
                }

                hostingPlanListResult = webSiteManagementClient.WebHostingPlans.List(webSpaceName);

                LogToSignalR("Creating your web site", webSiteName);

                var webSiteCreateResult = webSiteManagementClient.WebSites.Create(
                    webSpaceName,
                    new WebSiteCreateParameters
                    {
                        Name = webSiteName,
                        ServerFarm = hostingPlanListResult.WebHostingPlans.First().Name
                    });

                LogToSignalR("Getting site publishing settings", webSiteName);

                var profiles = webSiteManagementClient.WebSites.GetPublishProfile(webSpaceName, webSiteName);
                var webDeployProfile = profiles.First(x => x.MSDeploySite != null);

                if (Directory.GetFiles(webSiteSrcFolder, "deploytoazure.json").Any())
                {
                    var json = new StreamReader(System.IO.File.OpenRead(string.Format("{0}\\deploytoazure.json", webSiteSrcFolder))).ReadToEnd();
                    var deploymentModel = JsonConvert.DeserializeObject<DeployToModel>(json);
                    if (!string.IsNullOrEmpty(deploymentModel.SubdirectoryWithWebsite))
                    {
                        webSiteSrcFolder = string.Format("{0}\\{1}", webSiteSrcFolder, deploymentModel.SubdirectoryWithWebsite);
                    }
                }

                LogToSignalR("Publishing your site", webSiteName);

                new WebDeployPublishingHelper(
                    webDeployProfile.PublishUrl,
                    webDeployProfile.MSDeploySite,
                    webDeployProfile.UserName,
                    webDeployProfile.UserPassword,
                    webSiteSrcFolder
                    )
                    .PublishFolder();

                LogToSignalR("All finished!", webSiteName);
            }
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var token = GetAccessToken();

            // todo: add better error handling around this next line
            var activeSubscription = GetSubscriptions().First(x => x.ActiveDirectoryTenantId == TenantId);
            var webSpaces = GetWebSpaces(token, activeSubscription.SubscriptionId);
            var gitRepoUrl = string.Empty;

            if (string.IsNullOrEmpty(token))
            {
                // todo: let the user know they need to re-auth to get a new token
            }

            // think about this logic, it isn't bullet-proof...
            if (!string.IsNullOrEmpty(Request.ServerVariables["HTTP_REFERER"]))
                gitRepoUrl = string.Format("{0}.git", Request.ServerVariables["HTTP_REFERER"]);
            else
            {
                if (string.IsNullOrEmpty(Request.QueryString["giturl"]))
                    gitRepoUrl = Request.QueryString["giturl"];
            }

            return View(new DeployViewModel
            {
                AccessToken = token,
                Subscription = activeSubscription,
                WebSpaces = webSpaces,
                GitRepositoryUrl = gitRepoUrl
            });
        }

        // todo: clean up the parameters with an object
        [HttpPost]
        public JsonResult Index(string webSpace,
            string gitUrl,
            string webSiteName)
        {
            var token = GetAccessToken();
            var activeSubscription = GetSubscriptions().First(x => x.ActiveDirectoryTenantId == TenantId);

            try
            {
                if (string.IsNullOrEmpty(token))
                {
                    // todo: let the user know they need to re-auth to get a new token
                }

                var sourceFolder = this.CloneSiteRepository(gitUrl, webSiteName);

                this.CreateAndDeployWebsite(webSpace,
                    webSiteName,
                    sourceFolder,
                    activeSubscription.SubscriptionId,
                    token);
            }
            catch (Exception ex)
            {

            }

            return Json(new
            {
                success = true,
                siteUrl = string.Format("http://{0}.azurewebsites.net", webSiteName)
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult CheckWebSiteName(string webSiteName)
        {
            var token = GetAccessToken();

DeployToAzure/Views/Deploy/Index.cshtml
@model DeployToAzure.Models.DeployViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    select::-ms-expand {
        width: 12px;
        border: none;
        background: #fff;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="jumbotron">
                <h1>Deploy to Azure</h1>
                @using (Html.BeginForm("Index", "Deploy", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    <div class="form-group">
                        <span class="control-label col-xs-2">Geo Region</span>
                        <div class="col-xs-9">
                            @Html.DropDownList("webSpace", Model.WebSpaces.Select(x => new SelectListItem { Text = x.GeoRegion, Value = x.WebSpaceName }), new { id = "webSpace", @class = "form-control col-xs-9" })
                        </div>
                    </div>

                    <div class="form-group">
                        <span for="gitUrl" class="control-label col-xs-2">Git URL</span>
                        <div class="col-xs-9">
                            <input required="required" type="text" id="gitUrl" name="gitUrl" class="form-control" value="@Model.GitRepositoryUrl" />
                        </div>
                    </div>

                    <div class="form-group has-warning" id="siteNameCheckForm">
                        <span class="col-xs-2 control-label">Site Name</span>
                        <div class="col-xs-9">
                            <div class="input-group col-xs-9">
                                <input required="required" type="text" id="webSiteName" name="webSiteName" class="form-control" placeholder="foo">
                            </div>
                            <span class="help-block" id="siteNameResult">Please name your new Website</span>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-xs-offset-2 col-xs-9">
                            <button id="submitButton" class="btn btn-info" type="button">Deploy to Azure</button>
                            <img id="spinner" src="~/Content/spinner.gif" style="width: 24px; height: 24px; margin-left: 5px;" />
                            <a href="#" id="viewSiteLink" class="btn btn-success" target="_blank" style="margin-left: 5px;">View Site</a>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="col-md-4">
            <div class="jumbotron" id="statusContainer">
                <h2>Status</h2>
                <ul id="status" class="list-unstyled">
                    <li>Waiting for input</li>
                </ul>
            </div>
        </div>
    </div>

</div>


@section scripts
{
    <script src="~/Scripts/jquery.signalR-2.0.2.js"></script>
    <script type="text/javascript">
        $(function () {
            // disable the button to start off and hide the view site button
            $('#submitButton').attr('disabled', 'disabled');
            $('#viewSiteLink').hide();
            $('#spinner').hide();
            $('#statusContainer').hide();

            // connect the status hub
            var con = $.hubConnection();
            var hub = con.createHubProxy('statusHub');
            hub.on('messageTraced', function (message) {
                $('#status').append('<li>' + message + '</li>');
            });
            con.start();

            // post the form
            $('#submitButton').click(function () {
                $('#spinner').show();
                $('#statusContainer').slideDown();
                $('#submitButton').html('Deploying to Azure');
                hub.invoke('addToGroup', $('#webSiteName').val())

                $.post('/deploy/Index', {
                    webSpace: $('#webSpace').val(),
                    gitUrl: $('#gitUrl').val(),
                    webSiteName: $('#webSiteName').val()
                }, function (result) {

                    $('#spinner').hide();
                    $('#statusContainer').slideUp();
                    $('#submitButton').html('Deployed to Azure');

                    if (result.success == true) {
                        $('#viewSiteLink').attr('href', 'http://' + $('#webSiteName').val() + '.azurewebsites.net');
                        $('#viewSiteLink').fadeIn();
                    }
                });
            });

            // handle the status of the form validation and messaging (could be refactored)
            $('#webSiteName').change(function () {
                $('#siteNameCheckForm').removeClass('has-warning');
                $('#siteNameCheckForm').removeClass('has-success');
                $('#siteNameCheckForm').removeClass('has-error');
                $('#siteNameCheckForm').addClass('has-warning'); 
                $('#siteNameResult').text('Checking "' + $('#webSiteName').val() + '.azurewebsites.net" for availability.');

                $.get('/deploy/CheckWebSiteName?webSiteName=' + $('#webSiteName').val(), function (data) {
                    if (data.isSiteAvailable == true) {
                        $('#siteNameCheckForm').removeClass('has-warning');
                        $('#siteNameCheckForm').removeClass('has-success');
                        $('#siteNameCheckForm').removeClass('has-error');
                        $('#siteNameCheckForm').addClass('has-success');
                        $('#siteNameResult').text('Site "' + $('#webSiteName').val() + '.azurewebsites.net" is available.');
                        $('#submitButton').removeAttr('disabled');
                    }
                    else {
                        $('#siteNameCheckForm').removeClass('has-warning');
                        $('#siteNameCheckForm').removeClass('has-success');
                        $('#siteNameCheckForm').removeClass('has-error');
                        $('#siteNameCheckForm').addClass('has-error');
                        $('#siteNameResult').text('Site "' + $('#webSiteName').val() + '.azurewebsites.net" is unavailable.');
                        $('#submitButton').attr('disabled', 'disabled');
                    }
                });
            });
        });
    </script>
}